name: trigger

on:
  schedule:
    - cron:  '* * * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo " Hello vishwanath 123"
