name: Workflow3

# Controls when the workflow will wor
on:
  workflow_dispatch:
    inputs: 
      workflow4_name:
        description: 'Workflow4 Name for Triggering'
        required: true
        default: 'Workflow4'
      
      workflow4_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'vkele12'
      
      workflow4_repo_github:
        description: 'GitHub Repository Name'
        required: true
        default: 'repo2'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
   # env: 
   #   pat_token: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
   #   payload_Baseline_Number: "BSL_001"
   #   payload_Baseline_Revision: "zsfdgsdbgngffdwdx1dxvv2"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: display message
      run: echo " Hi Vishwanath ,yes "
